#spring:
#  shell:
#    interactive:
#      enabled: false
#  datasource:
#    data: test_db_data.sql
#    driver-class-name: org.h2.Driver
#    initialization-mode: always
#
spring:
  datasource:
    initialization-mode: always
    data: data.sql
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true